#This is a basic workflow to help you get started with Actions

name: scp connection
on:
  push:
    branches: [ master ]
#jobs:
 # terraform:
  #  name: 'Terraform
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key

  deploy:
    name: SCP files to remote server
    runs-on: ubuntu-latest
    steps:
      - name: SCP files via ssh key
        uses: nogsantos/scp-deploy@master
        env:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ##port: ${{ secrets.PORT }}
        with:
          source: './k8s/*'
          target: '/home/azureuser/'
